user_string = input("Write your string: ")

print(user_string[2])
print(user_string[-2])
print(user_string[:5])
print(user_string[:-2])
print(user_string[::2])
print(user_string[1::2])
print(user_string[::-1])
print(user_string[::-2])
print(len(user_string))